### ISSUE TITLE
Cordova Plugin for Fuse

### ISSUE THREAD

**Issue by rodenp** [cjpearson/cordova-plugin-nativescript#1]
HI,
I really like your cordova plugin for nativecript and was wondering if you would be able to assist with creating a similar plugin that basically allowed access to cordova plugins to other javascript frameworks. 

I am using the fusetools platform at the moment, and currently they do not support cordova plugins. What I would like to be able to do is to install a plugin similar to your nativescript one that would allow me to access cordova plugins.

Is it possible to create a thin layer on top of cordova that would allow access to plugins that do not require dom access?

Or do i have to install the full cordova and make the app a combined fuse and cordova app?

Many thanks and once again great work.

cheers
Peter

**Comment by cjpearson** [comment]
Hi @rodenp, I'm not sure how feasible that would be. Most cordova plugins do not operate on the DOM, but do expect to be initialized with a webview and there doesn't seem to be a webview in fusetools. What sort of cordova plugins are you planning on using?

This plugin is only one way. It allows the cordova webview to use the nativescript engine, but it does not allow nativescript code to use other cordova plugins.
